data driven testing framework using selenium 4
knoldus/selenium4-datadriven-framework pull request #1
Opened 2021-12-17 07:57 UTC by sujeetsrivastava1997

2022-01-31 08:28 UTC, gauravknoldus commented on README.md
> +Clone the repository on your local system.
Please add git command to clone the repository.

2022-01-31 08:29 UTC, gauravknoldus commented on README.md
> +We have used a dummy web application and excel test data in this template but you can change it accordingly.
Please provide the URL of dummy web application.

2022-01-31 08:30 UTC, gauravknoldus commented on pom.xml
> +
Remove these empty lines

2022-01-31 08:31 UTC, gauravknoldus commented on src/test/java/DDTF/WordPressLogin.java
> +
No more empty lines, it increasing line of code.

2022-01-31 08:32 UTC, gauravknoldus commented on src/test/java/DDTF/WordPressLogin.java
> +        System.out.println(username);
Use logger instead of using system.out.println

2022-01-31 08:33 UTC, gauravknoldus commented on src/test/java/DDTF/WordPressLogin.java
> +        //System.setProperty("webdriver.chrome.driver", "src/test/chromedriver_linux64/chromedriver");
Only info comment should be there, commented code should not be there

2022-01-31 08:36 UTC, gauravknoldus commented on src/test/java/DDTF/WordPressLogin.java
> +        ExcelDataConfig config = new ExcelDataConfig("TestData/testdata.xlsx");
Read this file path from resources folder.

2022-01-31 08:36 UTC, gauravknoldus commented on src/test/java/lib/ExcelDataConfig.java
> +package lib;
remove empty lines.

2022-01-31 08:37 UTC, gauravknoldus commented on src/test/resources/application.conf
> +
Remove empty line

2022-01-31 08:37 UTC, gauravknoldus commented on target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/createdFiles.lst
> +lib/ExcelDataConfig.class
Exclude these target folder in git.ignore

2022-01-31 08:38 UTC, gauravknoldus commented on target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/inputFiles.lst
> +/home/knoldus/Documents/selenium4-datadriven-framework/src/test/java/DDTF/WordPressLogin.java
Exclude these target folder in git.ignore

2022-01-31 08:38 UTC, gauravknoldus commented on target/surefire-reports/DDTF.WordPressLogin.txt
> +-------------------------------------------------------------------------------
Exclude these target folder in git.ignore

2022-01-31 08:38 UTC, gauravknoldus commented on target/surefire-reports/Surefire suite/Surefire test.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Exclude these target folder in git.ignore

2022-01-31 08:38 UTC, gauravknoldus commented on target/surefire-reports/Surefire suite/testng-failed.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Exclude these target folder in git.ignore

2022-01-31 08:39 UTC, gauravknoldus commented on target/surefire-reports/TEST-DDTF.WordPressLogin.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Exclude these target folder in git.ignore

2022-01-31 08:39 UTC, gauravknoldus commented on target/surefire-reports/emailable-report.html
> +<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "https://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
Exclude these target folder in git.ignore

2022-01-31 08:42 UTC, gauravknoldus requested changes
Please addres the provided review comments. @sujeetsrivastava1997 
1) Unnecessary empty lines should not be there
2) Commented code should not be there, only info comment should be there.
3) No hardcoded values, everything should be drived from configurations.
4) No target folder should be checkdin to the repository.

2022-02-01 04:20 UTC, sujeetsrivastava1997 commented on README.md
> +Clone the repository on your local system.
Added git command to clone repo

2022-02-01 04:20 UTC, sujeetsrivastava1997 commented on README.md
> +We have used a dummy web application and excel test data in this template but you can change it accordingly.
Provided the URL of dummy web application

2022-02-01 04:20 UTC, sujeetsrivastava1997 commented on pom.xml
> +
Removed empty lines

2022-02-01 04:21 UTC, sujeetsrivastava1997 commented on src/test/java/DDTF/WordPressLogin.java
> +
Removed empty lines

2022-02-01 04:21 UTC, sujeetsrivastava1997 commented on src/test/java/DDTF/WordPressLogin.java
> +        System.out.println(username);
Used logger instead of using system.out.println

2022-02-01 04:22 UTC, sujeetsrivastava1997 commented on src/test/java/DDTF/WordPressLogin.java
> +        //System.setProperty("webdriver.chrome.driver", "src/test/chromedriver_linux64/chromedriver");
removed commented code

2022-02-01 04:22 UTC, sujeetsrivastava1997 commented on src/test/java/DDTF/WordPressLogin.java
> +        ExcelDataConfig config = new ExcelDataConfig("TestData/testdata.xlsx");
changed the file path in resources folder

2022-02-01 04:23 UTC, sujeetsrivastava1997 commented on src/test/java/lib/ExcelDataConfig.java
> +package lib;
removed empty files

2022-02-01 04:23 UTC, sujeetsrivastava1997 commented on src/test/resources/application.conf
> +
removed empty lines

2022-02-01 04:23 UTC, sujeetsrivastava1997 commented on target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/createdFiles.lst
> +lib/ExcelDataConfig.class
excluded target folder

2022-02-01 04:23 UTC, sujeetsrivastava1997 commented on target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/inputFiles.lst
> +/home/knoldus/Documents/selenium4-datadriven-framework/src/test/java/DDTF/WordPressLogin.java
excluded target folder

2022-02-01 04:23 UTC, sujeetsrivastava1997 commented on target/surefire-reports/DDTF.WordPressLogin.txt
> +-------------------------------------------------------------------------------
excluded target folder

2022-02-01 04:24 UTC, sujeetsrivastava1997 commented on target/surefire-reports/Surefire suite/Surefire test.xml
> +<?xml version="1.0" encoding="UTF-8"?>
excluded target folder

2022-02-01 04:24 UTC, sujeetsrivastava1997 commented on target/surefire-reports/Surefire suite/testng-failed.xml
> +<?xml version="1.0" encoding="UTF-8"?>
excluded target folder

2022-02-01 04:24 UTC, sujeetsrivastava1997 commented on target/surefire-reports/TEST-DDTF.WordPressLogin.xml
> +<?xml version="1.0" encoding="UTF-8"?>
excluded target folder

2022-02-01 04:24 UTC, sujeetsrivastava1997 commented on target/surefire-reports/emailable-report.html
> +<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "https://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
excluded target folder

2022-02-01 04:25 UTC, sujeetsrivastava1997 commented
Addressed above mentioned review comments and applied changes according to it.

2022-02-03 11:54 UTC, gauravknoldus approved these changes

2022-02-03 11:54 UTC, merged